spring.application.name=PARCIAL
server.port=8113

spring.datasource.url=jdbc:mysql://brpicroudvwfwunydn2t-mysql.services.clever-cloud.com:3306/brpicroudvwfwunydn2t?useSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=u6lxcrlmflnn2xw1
spring.datasource.password=Kz94JR5rRGu6XU2HU2cN
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Dialecto correcto para Hibernate 7 + MySQL 8
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000

# Sesiones
server.servlet.session.timeout=30m
app.upload.dir=C:/Parcial/comprobantes
